- hosts: localhost
  become: yes
  tasks:
   - name: Install Git
     yum: name=git state=present
   - name: git clone
     git:
      repo: 'https://github.com/p2pro-DevOps/maven-web-application-master.git'
      dest: /home/ansible/gradle-web-app